language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t parikshitsm/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true parikshitsm/react-test npm test -- --coverage

after_success:
  - docker build -t parikshitsm/multi-client ./client
  - docker build -t parikshitsm/multi-nginx ./nginx
  - docker build -t parikshitsm/multi-server ./server
  - docker build -t parikshitsm/multi-worker ./worker
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these production images and push them to docker hub
  - docker push parikshitsm/multi-client
  - docker push parikshitsm/multi-nginx
  - docker push parikshitsm/multi-server
  - docker push parikshitsm/multi-worker